---
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes
  become: yes
    
- rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  become: yes
    
- yum: name=jq
  become: yes
  
- name: Install needed prerequisites
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - cifs-utils
    - util-linux
    - coreutils
  become: yes

- name: Create fstab/cifs plugin directory
  file:
    path: "{{ k8s_volume_plugins_directory }}/{{ fstab_cifs_directory }}"
    state: directory
    mode: 0755
  become: yes

- name: Download fstab/cifs plugin binary
  get_url:
    url: "{{ fstab_cifs_download_url }}"
    dest: "{{ k8s_volume_plugins_directory }}/{{ fstab_cifs_directory }}"
    mode: 0755
  become: yes

- name: Initialize fstab/cifs plugin
  environment:
    VOLUME_PLUGIN_DIR: "{{ k8s_volume_plugins_directory }}"
  shell: "$VOLUME_PLUGIN_DIR/{{ fstab_cifs_directory }}/cifs init"
  args:
    executable: /bin/bash
  register: cifs_initialization
  become: yes

- name: Verify fstab/cifs initialization
  debug:
    var: cifs_initialization.stdout